remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: MHC MTA Datathon Submission
description: An analysis on various ACE Routes and how the Suwbay system can impact tickets.